name: example
# description: Example Flutter Project for pinterest_nav_bar package.
publish_to: "none"
# version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  pinterest_nav_bar:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  pinterest_nav_bar:
    path: ../

flutter:
  uses-material-design: true
